title: Grace Commons
description: A shared library of business logic patterns expressed as structured natural language specifications.
theme: minima

author: Scott Romack

show_excerpts: false

markdown: kramdown
