# fly.toml app configuration file generated for grace-commons-clinical-trial3-rosy-orchard-3313 on 2026-05-22T21:02:55-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'beacon-clinical'
primary_region = 'sjc'

[build]

[env]
  DB_PATH = '/data/beacon.sqlite'
  PORT = '8000'

[[mounts]]
  source = 'beacon_data'
  destination = '/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 512
