#!/usr/bin/env python3
"""
tools/taxonomy/generate_views.py — emit the generated browse-by-overlay catalog
that replaces the dissolved per-category atom folders (see atoms/TAXONOMY.md).

Consumes the usage-derived index (reverse_index.build_index) and writes
atoms/index.md: the "Atomic Concepts" landing, now a set of **lenses** over the
Intent Graph — regulated, security, by-standard, by-domain, uncomposed — plus a
full table of every atom with its derived overlays. It reports USAGE, not essence
(`HIPAA via audit-trail`; `composed by: (none yet)`), exactly as the index does.

This is the view half of the seam described in tools/taxonomy/README.md: the
index (reverse_index.py) is the model; this is the generated artifact. Mirrors
tools/recipe/generate_recipe.py — derive the view from canonical source rather
than hand-maintain it. Read-only except for the single file it writes.

Usage:  python3 tools/taxonomy/generate_views.py [repo-root]   # writes <root>/atoms/index.md
"""
import sys, re, pathlib
from collections import defaultdict

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from reverse_index import build_index  # noqa: E402  (same directory)


def atom_title(root, slug):
    p = root / "atoms" / f"{slug}.md"
    try:
        t = p.read_text(encoding="utf-8")
    except OSError:
        return slug
    if t.startswith("---"):
        end = t.find("\n---", 3)
        m = re.search(r"^\s*title:\s*(.+?)\s*$", t[3:end if end != -1 else len(t)], re.M)
        if m:
            return m.group(1).strip()
    return slug


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    root = pathlib.Path(args[0]) if args else pathlib.Path(".")
    index, comps = build_index(root)
    atoms = sorted(index)
    reg_comps = sorted(c["name"] for c in comps if c["regulated"])
    edges = sum(len(c["atoms"]) for c in comps)

    def link(slug):
        return f"[{atom_title(root, slug)}](./{slug}.md)"

    L = []
    P = L.append
    P("---")
    P("title: Atomic Concepts")
    P("nav_order: 6")
    P("has_children: true")
    P("permalink: /atoms/")
    P("has_toc: true")
    P("toc: true")
    P("---")
    P("")
    P("<!-- GENERATED by tools/taxonomy/generate_views.py from tools/taxonomy/reverse_index.py.")
    P("     Do not hand-edit — regenerate. Atom classification is DERIVED: overlays from the")
    P("     composition graph, domain from each atom's own frontmatter. See atoms/TAXONOMY.md. -->")
    P("")
    P("# Atomic Concepts")
    P("")
    P('<details markdown="block">')
    P("  <summary>Table of contents</summary>")
    P("  {: .text-delta }")
    P("1. TOC")
    P("{:toc}")
    P("</details>")
    P("")
    P("The freestanding semantic units of Grace Commons — each fully specifiable without naming "
      "another atom. Atoms are stored flat (`atoms/<name>.md`); their classification is not a "
      "folder but a set of **lenses** over the Intent Graph. Overlays (regulated · security · "
      "standards) are read off the composition graph and **report usage, not essence** — a "
      "standard shows as *HIPAA via audit-trail*, an uncomposed atom as *composed by: (none yet)*, "
      "never a bare boolean. **Domain** is the one intrinsic axis: an optional, EOS-gated tag, "
      "default absent. The design and its rationale are in [the taxonomy note](./TAXONOMY.md).")
    P("")
    P(f"_{len(comps)} compositions ({len(reg_comps)} regulated) · {len(atoms)} atoms · {edges} "
      "composition→atom edges. Generated from `tools/taxonomy/reverse_index.py`; regenerate with "
      "`python3 tools/taxonomy/generate_views.py .`_")
    P("")

    # ---- full table -------------------------------------------------------
    P("## All atoms")
    P("")
    P("| Atom | Domain | Regulated | Security | Composed by |")
    P("|---|---|---|---|---|")
    for a in atoms:
        e = index[a]
        ov = e["overlays"]
        dom = e["domain"] or "—"
        reg = f"yes ({len(ov['regulated_by'])})" if ov["regulated_by"] else "—"
        sec = "yes" if ov["security"] else "—"
        cb = ", ".join(e["composed_by"]) if e["composed_by"] else "*(none yet)*"
        P(f"| {link(a)} | {dom} | {reg} | {sec} | {cb} |")
    P("")

    # ---- lens: regulated --------------------------------------------------
    reg_atoms = [a for a in atoms if index[a]["overlays"]["regulated_by"]]
    P("## Lens — regulated")
    P("")
    P("Atoms that a regulated composition (one carrying a `## Generation acceptance` section) "
      "composes. Derived, attributed per composer.")
    P("")
    for a in reg_atoms:
        P(f"- {link(a)} — via {', '.join(index[a]['overlays']['regulated_by'])}")
    P("")

    # ---- lens: security ---------------------------------------------------
    sec_atoms = [a for a in atoms if index[a]["overlays"]["security"]]
    P("## Lens — security")
    P("")
    P("An overlay, not a domain: an atom carries it iff it derives an identity / access / "
      "crypto-family standard (NIST 800-63/53/207, OWASP ASVS, SCIM, FIPS 180-4). Cross-cutting "
      "and multi-valued — an atom can hold it alongside any domain.")
    P("")
    for a in sec_atoms:
        P(f"- {link(a)}")
    P("")

    # ---- lens: by domain --------------------------------------------------
    P("## Lens — by domain")
    P("")
    P("The one intrinsic axis. A domain earns a tag only when stripping it fails to leave a "
      "freestanding, domain-neutral primitive (the EOS test); default absent. The system is "
      "correct with zero domain tags — domain is additive, never load-bearing.")
    P("")
    dom_map = defaultdict(list)
    for a in atoms:
        if index[a]["domain"]:
            dom_map[index[a]["domain"]].append(a)
    if dom_map:
        for d in sorted(dom_map):
            P(f"- **{d}**: " + ", ".join(link(a) for a in dom_map[d]))
    else:
        P("- *(no atom carries a domain tag yet)*")
    P("")

    # ---- lens: by standard ------------------------------------------------
    P("## Lens — by standard")
    P("")
    P("The union of standards each atom's composers carry, attributed per composer in the atom's "
      "own page.")
    P("")
    std_atoms = defaultdict(set)
    for a in atoms:
        for _comp, stds in index[a]["overlays"]["standards_by_composer"].items():
            for s in stds:
                std_atoms[s].add(a)
    for s in sorted(std_atoms):
        P(f"- **{s}**: " + ", ".join(link(a) for a in sorted(std_atoms[s])))
    P("")

    # ---- lens: uncomposed -------------------------------------------------
    unc = [a for a in atoms if not index[a]["composed_by"]]
    P("## Lens — uncomposed")
    P("")
    P("Atoms no composition yet composes. The overlays say nothing about them — an honest gap, "
      "not a claim of non-regulation.")
    P("")
    for a in unc:
        P(f"- {link(a)}")
    P("")
    P("---")
    P("")
    P("For structured assemblies of atoms, see [Compositions](../compositions/).")
    P("")

    out = root / "atoms" / "index.md"
    out.write_text("\n".join(L), encoding="utf-8")
    sys.stderr.write(
        f"wrote {out}: {len(atoms)} atoms, {len(reg_atoms)} regulated, "
        f"{len(sec_atoms)} security, {len(dom_map)} domain(s), {len(unc)} uncomposed\n"
    )


if __name__ == "__main__":
    main()
